const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descripcion: "high quality product",
    },
    {
      _id: "2",
      name: "Adidas Slim Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 130,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      descripcion: "high quality product",
    },
    {
      _id: "3",
      name: "Lacoste Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 150,
      countInStock: 0,
      brand: "Lacoste",
      rating: 3,
      numReviews: 9,
      descripcion: "high quality product",
    },
    {
      _id: "4",
      name: "Puma Slim Shirt",
      category: "Shirts",
      image: "/images/p4.jpg",
      price: 90,
      countInStock: 15,
      brand: "Puma",
      rating: 4.8,
      numReviews: 6,
      descripcion: "high quality product",
    },
    {
      _id: "5",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 100,
      countInStock: 12,
      brand: "Nike",
      rating: 4.5,
      numReviews: 8,
      descripcion: "high quality product",
    },
    {
      _id: "6",
      name: "Adidas Slim Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 80,
      countInStock: 0,
      brand: "Nike",
      rating: 4.5,
      numReviews: 9,
      descripcion: "high quality product",
    },
  ],
};

export default data;
